---

- name: Cisco APIC controller EPG and Contracts configuration
  hosts: apic
  connection: local
  gather_facts: no
  vars_files: vars/main.yml  
  tasks:
    - name: EPG configuration
      cisco.aci.aci_epg:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        validate_certs: no
        tenant: "{{ aci_epg.tenant }}"
        ap: "{{ aci_epg.ap }}"
        epg: "{{ aci_epg.epg | default(inventory_hostname)  }}"
        description: "{{ aci_epg.description | default(omit) }}"
        bd: "{{ aci_epg.bd }}"
        state: present

    - name: Bind EPG to contract
      cisco.aci.aci_epg_to_contract: 
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        validate_certs: no
        epg: "{{ aci_epg.epg | default(inventory_hostname)  }}"
        contract_type: "{{ item.contract_type | default('provider') }}"
        contract: "{{ item.contract }}"
        priority: "{{ item.priority | default(omit) }}"
        tenant: "{{ aci_epg.tenant }}"
        ap: "{{ aci_epg.ap }}"
        state: "{{ item.state | default(omit) }}"
      loop: "{{ aci_epg.contracts }}"
      loop_control:
        label: "{{ item.contract }} ==> {{ item.state | default('present') }}"
      when: aci_epg.contracts is defined
